// Generated by CoffeeScript 1.10.0
(function() {
  describe('Unit test:', function() {
    return it('should be true', function() {
      return expect(true).toBe(true);
    });
  });

}).call(this);
