#!/bin/bash
bin/rimraf client/public
NODE_ENV=production ./bin/webpack --config config/client.config.js
./bin/webpack --config config/client.config.js -d
./bin/webpack --config config/server.config.js -d
node tasks/copy-replace.js
